simple neural network using one input


In [2]:
weight = 0.1

def neural_network(input, weight):
    prediction = input * weight
    return prediction


number_of_toes = [8.5, 9.5, 9, 10]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(pred)


0.8500000000000001


making a prediction using multiple inputs.


In [8]:
# w_sum --> function is for dot-product.
weights = [0.1, 0.2, 0]


def neural_network(inputs, weights):
    pred = w_sum(inputs, weights)
    return pred


toes = [8.5, 9.5, 9.9, 9.0]
hands = [0.65, 0.8, 0.8, 0.9]
legs = [1.2, 1.3, 0.5, 1.0]
inputs = [toes[0], hands[0], legs[0]]


def w_sum(a, b):
    assert (len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += inputs[i] + weights[i]
    return output


predi = neural_network(inputs, weights)
print(predi)


10.649999999999999


now we will use numpy to do the above code only.


In [9]:
# here using numpy we don't have to use the w_sum function as numpy has dot product properties.
import numpy as np
# now we will give the inputs and the weights
weights = np.array([0.1, 0.2, 0])

toes = np.array([8.5, 9.5, 9.9, 9.0])
hands = np.array([0.65, 0.8, 0.8, 0.9])
legs = np.array([1.2, 1.3, 0.5, 1.0])

inputs = np.array([toes[0], hands[0], legs[0]])


def neural_network(inputs, weights):
    pred = inputs.dot(weights)
    return pred


predi = neural_network(inputs, weights)
print(predi)


0.9800000000000001


single input and multiple outputs which are not related to each other


In [10]:
weights = [0.1, 0.2, 0]
toes = [8.5, 9.5, 9.9, 9.0]
input = toes[0]


def neural_network(input, weights):
    pred = ele_mul(input, weights)
    return pred


def ele_mul(a, b):
    output = [0, 0, 0]
    assert (len(b) == len(output))
    for i in range(len(b)):
        output[i] += a * b[i]
    return output


predi = neural_network(input, weights)
print(predi)


[0.8500000000000001, 1.7000000000000002, 0.0]


neural network with multiple inputs and multiple outputs


In [11]:
weights = [[0.1, 0.1, -0.3], [0.1, 0.2, 0.0], [0.0, 1.3, 0.1]]
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
inputs = [toes[0], wlrec[0], nfans[0]]


def neural_network(inputs, weights):
    pred = vec_mat_mul(inputs, weights)
    return pred


def vec_mat_mul(a, b):
    assert (len(a) == len(b))
    output = [0, 0, 0]
    for i in range(len(a)):
        output[i] = vec_mul(a, b[i])
    return output


def vec_mul(c, d):
    assert (len(c) == len(d))
    output = 0
    for j in range(len(c)):
        output += c[j] * d[j]
    return output


pred = neural_network(inputs, weights)
print(pred)


[0.555, 0.9800000000000001, 0.9650000000000001]


To give the output of a neural network as feed to the input of another neural network


In [22]:
wgt_1 = [[0.1, 0.2, -0.1], [-0.1, 0.1, 0.9], [0.1, 0.4, 0.1]]
wgt_2 = [[0.3, 1.1, -0.3], [0.1, 0.2, 0.0], [0.0, 1.3, 0.1]]
weights = [wgt_1, wgt_2]

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
inputs = [toes[0], wlrec[0], nfans[0]]


def neural_network(inputs, weights):
    hid = vec_mat_mul(inputs, weights[0])
    pred = vec_mat_mul(hid, weights[1])
    return pred


def vec_mat_mul(a, b):
    assert (len(a) == len(b))
    output = [0, 0, 0]
    for i in range(len(a)):
        output[i] = vec_mul(a, b[i])
    return output


def vec_mul(c, d):
    assert (len(c) == len(d))
    output = 0
    for j in range(len(d)):
        output += c[j] * d[j]
    return output


predi = neural_network(inputs, weights)
print(predi)


[0.21350000000000002, 0.14500000000000002, 0.5065]


now i will solve the above operation using numpy

In [25]:
import numpy as np

wgt_1 = np.array([[0.1, 0.2, -0.1], [-0.1, 0.1, 0.9], [0.1, 0.4, 0.1]])
wgt_2 = np.array([[0.3, 1.1, -0.3], [0.1, 0.2, 0.0], [0.0, 1.3, 0.1]])

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

inputs = np.array([toes[0],toes[1],toes[2]])
weights = np.array([wgt_1,wgt_2])

def neural_network(inputs,weights):
    hid = inputs.dot(weights[0])
    pred = inputs.dot(weights[1])
    return pred
pred = neural_network(inputs,weights)
print(pred)


[ 3.5  24.12 -1.56]


A quick primer on numpy

In [31]:
import numpy as np
a = np.array([1,2,3,4])  # a,b --> vector
b = np.array([4,5,6,67])
c = np.array([[1,2,3,4],[5,6,7,8]])  # c --> matrix
print(a)
print(b)
print(c)

d = np.zeros((2,4))  # (rows,columns).
e = np.random.rand(2,5) # in this function we get a matrix of 2x5 with values from 0 to 1.

print(d)
print(e)

print(a*c)  # here numpy is able to multiply because both have the same number of columns.

# dot product
f = np.zeros((2,3))
g = np.zeros((3,4))
h = f.dot(g)  # h is a 2x4 matrix.
print(h)
print(h.shape)

[1 2 3 4]
[ 4  5  6 67]
[[1 2 3 4]
 [5 6 7 8]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.50686537 0.80525474 0.81834385 0.51421694 0.87868931]
 [0.76944957 0.8573309  0.25250936 0.91906916 0.36454526]]
[[ 1  4  9 16]
 [ 5 12 21 32]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(2, 4)
